edit today's note with vim
tomlockwood/dn pull request #3
Opened 2019-11-01 17:22 UTC by djwgit

edit today's note with vim

2019-11-03 05:31 UTC, tomlockwood commented
Looks good! Can we maybe include a `dnoe` command which takes one argument, which is a date, and opens that dn file in the editor? Thanks!

2019-11-03 15:50 UTC, djwgit commented
good idea, @tomlockwood
- added dnoe
- updated readme
ready for review...

2019-11-03 22:55 UTC, tomlockwood requested changes
LGTM with one proviso.  I'd prefer the commands are consistently documented in the README.  My suggestion is move the comment about `dnoe` allowing file selection into the README and delete the comments on both in `dn`.  Make that change and I'll merge!!!

Thanks!

2019-11-04 05:32 UTC, tomlockwood commented on dn
> +# if no date given, vim lists the ~/dn folder, then pick one to edit
To make it clear what I'm talking about in my PR comment - I suggest removing this and the other command documentation here into the README.

2019-11-04 14:30 UTC, tomlockwood commented
Awesome, thanks!

2019-11-04 14:30 UTC, merged